services:
  blindup:
    container_name: blindup
    build: .
    ports:
      - "8500:8000"
    environment:
      BLINDUP_DB_PATH: /data/blindup.db
      BLINDUP_LIBRARY_ROOT_PATH: /music-library
      BLINDUP_COVERS_DIR: /covers
    volumes:
      - blindup-data:/data
      - ${BLINDUP_HOST_MUSIC_LIBRARY}:/music-library
      - ${BLINDUP_HOST_COVERS_DIR}:/covers

volumes:
  blindup-data:
